### ISSUE TITLE
LeetCode support

### ISSUE THREAD

**Issue by KargathEx** [slycelote/caide#50] opened 2021-12-13 16:23 UTC
Very much looking forward to

**Comment by slycelote** [comment] 2021-12-14 18:28
Possibly. Depends on how many people want it.

**Comment by mingy532** [comment] 2021-12-19 17:32
You reopened it to count how many people would expect leetcode support?

I don't know cf, but as far as I know, only novices like me will copy the code to the local IDE among Leetcode users, and Leetcode only needs to implement a class, so the IDE plug-in may not be very useful.

But I very much hope, if possible, to add support for simulation problems to Leetcode.
Like this
https://leetcode-cn.com/problems/stack-of-plates-lcci/

When the input data represents a function call and the corresponding parameters, the user can simply input the string itself, and then view the result at the i-th position, just like this.
https://github.com/mingy532/Trivial_thing/blob/master/Reflection_in_boost.cpp#L157

Instead of manually writing a lot of things such as
```cpp
Solution s;
s->func1(...)
s->func2(...)
...
```
If you plan to add support for leetcode, I hope you can add this feature.

**Comment by slycelote** [comment] 2021-12-22 06:24
The issue is open to track progress of this feature request, including user comments/plus-ones (although I can't give any ETA). Thanks for detailed explanation of simulation problems. I can't read Chinese, but I assume it's similar to [Dinner Plate Stacks](https://leetcode.com/problems/dinner-plate-stacks/).

**Comment by mingy532** [comment] 2021-12-22 07:44
I saw this question in the "crack the coding interview". The Chinese site LeetCode puts all the questions in this book into one topic, so I don't know its official title number.
They are indeed the same problem, thank you for taking the time to find it.

**Comment by slycelote** [comment] 2022-01-27 07:27
@KargathEx I added basic support for LeetCode and published a beta release [here](https://github.com/slycelote/caide/releases/tag/v2.10.0-beta1). I'd appreciate if you could test this out.

Regarding "simulation problems" -- do you have more examples, or maybe there's a general way to search for them?

Note that quite a few LeetCode problems involve custom structures, like TreeNode. Those are not yet supported either.

**Comment by KargathEx** [comment] 2022-01-27 10:36
Thanks, I will try it!
By the way, about the construction of custom data structures, you can refer to this
https://github.com/KargathEx/lc_debug/blob/main/lc.h

**Comment by KargathEx** [comment] 2022-01-27 10:39
simulation problems：https://leetcode.com/tag/simulation/

**Comment by KargathEx** [comment] 2022-01-27 10:41
Asking an unrelated question, how do you guys debug simulation problems while playing at codeforce, I find it too hard to keep track of its state in my head, and too tiring to manually write code that simulates function calls.

**Comment by KargathEx** [comment] 2022-01-27 11:11
https://www.boost.org/doc/libs/develop/libs/describe/doc/html/describe.html#example_json_rpc 
This one might work too, but I don't know how to handle the case where the input parameter is empty.

**Comment by KargathEx** [comment] 2022-01-27 14:43
It works fine.

but Error for this link:
https://leetcode.com/problems/k-highest-ranked-items-within-a-price-range/
![Uploading aaaaa.png…]()

**Comment by KargathEx** [comment] 2022-01-27 14:44
It works fine.

but Error for this link:
https://leetcode.com/problems/k-highest-ranked-items-within-a-price-range/
![aaaaa](https://user-images.githubusercontent.com/40135358/151381552-4bb5865d-bd1f-4417-b8ca-3ea2b66aca90.png)

**Comment by slycelote** [comment] 2022-01-30 17:06
> simulation problems：https://leetcode.com/tag/simulation/

Thanks! I found a better tag: https://leetcode.com/tag/design/

> how do you guys debug simulation problems while playing at codeforce, I find it too hard to keep track of its state in my head, and too tiring to manually write code that simulates function calls.

I don't really have experience with those, do you have example URLs?

> It works fine.
> 
> but Error for this link: https://leetcode.com/problems/k-highest-ranked-items-within-a-price-range/

Thanks! The problem is with multi-dimensional vectors. This will be fixed in release version.

**Comment by KargathEx** [comment] 2022-01-31 18:22
> Thanks, I will try it! By the way, about the construction of custom data structures, you can refer to this https://github.com/KargathEx/lc_debug/blob/main/lc.h

Sorry I just noticed that link is inaccessible , update:
https://github.com/luckystone60/leetcode-helper

**Comment by KargathEx** [comment] 2022-02-03 13:44
hi, can you please answer [this ](https://stackoverflow.com/questions/70972238/how-to-correctly-create-a-2d-vector-from-this-input)question？

**Comment by slycelote** [comment] 2022-03-07 04:28
@KargathEx I published another beta release that should support majority of LeetCode problems: https://github.com/slycelote/caide/releases/tag/v2.10.0-beta2

**Comment by slycelote** [comment] 2022-05-05 03:43
Published 2.10 release

**Closed by slycelote** 2022-05-05 03:43 UTC
