### ISSUE TITLE
caide doesn't open in Visual Studio 2019

### ISSUE THREAD

**Issue by ririyad** [slycelote/caide#24] opened 2020-01-29 16:49 UTC
I installed vscaide (version 2.4.1) extension in Visual Studio 2019. Restarted VS and tried again, caide doesn't open.
 
![1](https://user-images.githubusercontent.com/13316885/73377580-75d61900-42e9-11ea-82c5-d558379166b5.PNG)

**Comment by slycelote** [comment] 2020-01-29 17:55
Yes, unfortunately VsCaide is currently incompatible with VS2019. I recommend using VS2017 for the time being.

**Comment by slycelote** [comment] 2020-04-27 16:30
@ririyad Apparently VS made some changes and the extension is compatible again. Could you try with the latest VS version? Mine is 16.5.4.

**Comment by ririyad** [comment] 2020-04-28 05:05
@slycelote, just updated Visual Studio to 16.5.4. VsCaid was already installed. After finishing update, tried again, nothing happened. Then I uninstalled and downloaded again from the Extension Manager. Same result as before.

![image](https://user-images.githubusercontent.com/13316885/80449109-13200800-8940-11ea-9223-d20b391f45c4.png)

**Comment by slycelote** [comment] 2020-04-28 15:25
Could you try going to Tools -> Options -> Environment -> Extensions, and making sure that "Allow synchronous autoload of extensions" is selected?

**Comment by ririyad** [comment] 2020-04-29 12:47
You were right. After allowing synchronous autoload of extension, VsCaide now appears. Now while creating a caide solution an **Application Error** message is popping up.


![image](https://user-images.githubusercontent.com/13316885/80597502-c0cb0e00-8a49-11ea-921b-e71c95b39f40.png)

**Comment by slycelote** [comment] 2020-04-29 17:30
Hmm, interesting, so the whole Visual Studio crashes? Does it happen with VS 2017 too?
Does this happen immediately after you click "Create solution" button or do you get to choose the directory?

**Comment by ririyad** [comment] 2020-04-29 22:11
Exactly. It crashes with VS 2019 when I click 'Create Solution', show the directory and try to save the solution in that directory. And no, I didn't face this issue for VS 2017. Although it took a bit more time to load the extension initially, but it worked fine with 2017 version.

**Comment by slycelote** [comment] 2020-05-02 02:23
* Does it write anything at all in the chosen directory?
* Is there anything interesting in the file ActivityLog.xml just after the crash? (It should be located in `%APPDATA%\Microsoft\VisualStudio\16.0\ActivityLog.xml`)
* Could you please try the vsix [here](https://github.com/slycelote/caide/releases/tag/v2.4.2-pre)? This is my development build that doesn't use deprecated APIs.

**Comment by ririyad** [comment] 2020-05-05 05:42
- Yes, I tried it today and it seems working now. When I create a new caide solution, it created a sln file with all necessary files

![image](https://user-images.githubusercontent.com/13316885/81037183-9b178c00-8ec3-11ea-85c8-8dc9223a7183.png)
- Then I was able to parse a codeforces contest without any issue:

![image](https://user-images.githubusercontent.com/13316885/81037355-39a3ed00-8ec4-11ea-80a2-03dff2b13dd2.png)

- I checked ActivityLog,  and found this:

```
  <entry>
    <record>601</record>
    <time>2020/04/29 12:42:39.855</time>
    <type>Warning</type>
    <source>SyncAutoLoadedExtensions</source>
    <description>Extension &apos;VsCaide&apos; uses the &apos;synchronous autoload&apos; feature of Visual Studio. This feature will no longer be supported in a future Visual Studio 2019 update, at which point this extension will not work. Please contact the extension vendor to get an update. (UI Context: {adfc4e64-0397-11d1-9f4e-00a0c911004f} Package Guid: {8e97a36f-88cc-49ee-8e47-df660b4c7d83})</description>
  </entry>
```


- I didn't do any change in my VS settings except the last time to allow synchronous autoload. It didn't work that time, but now is working. Maybe I needed a restart of my PC, not sure here.

**Comment by slycelote** [comment] 2020-05-05 17:56
Yes, some pending Windows / VS updates could be the cause. Anyway, glad it's working for you! The usage of deprecated synchronous API will be fixed in the next VsCaide release.

**Closed by slycelote** 2020-05-05 17:56 UTC
